# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b565ca3175fc395515a74028056ff4d9940d98c4a1518c7fb056e760923e3132471c0a07b7a87693961c910b55e2bcc12cb24f8d819f8cbab99f9177980e27

test:
  secret_key_base: 340231463fff9f4ea45bdadd4c7f972d34105ea264a371356128b9a277e5efb61bff1a0d74b5ac79038db50a65701c7e6552917e7b494e0487cb3ba94c5b67c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
